Repository googleapis/python-documentai-toolbox, pull requests merged in 2023-06, with the labels that each got.

#124 feat: add convert_document_to_annotate_file_json
  google/cloud/documentai_toolbox/wrappers/document.py
  tests/unit/test_document.py
Labels: size: s

#110 refactor: Restructuring of classes to reduce duplication and increase readibility
  google/cloud/documentai_toolbox/converters/vision_helpers.py
  google/cloud/documentai_toolbox/wrappers/document.py
  google/cloud/documentai_toolbox/wrappers/entity.py
  google/cloud/documentai_toolbox/wrappers/page.py
  samples/snippets/table_sample.py
  samples/snippets/test_table_sample.py
  tests/unit/resources/missing_shard/Winnie_the_Pooh_50_Pages-0.json
  tests/unit/resources/missing_shard/Winnie_the_Pooh_50_Pages-1.json
  tests/unit/resources/missing_shard/Winnie_the_Pooh_50_Pages-3.json
  tests/unit/resources/missing_shard/Winnie_the_Pooh_50_Pages-4.json
  tests/unit/test_document.py
  tests/unit/test_entity.py
  tests/unit/test_gcs_utilities.py
  tests/unit/test_page.py
Labels: size: l

#123 feat: added hOCR export functionality
  google/cloud/documentai_toolbox/constants.py
  google/cloud/documentai_toolbox/converters/vision_helpers.py
  google/cloud/documentai_toolbox/wrappers/document.py
  google/cloud/documentai_toolbox/wrappers/page.py
  samples/snippets/test_export_images_sample.py
  samples/snippets/test_split_pdf_sample.py
  setup.py
  templates/hocr_xml_template.txt
  tests/unit/resources/0/toolbox_invoice_test-0.json
  tests/unit/resources/toolbox_invoice_test_0_hocr.xml
  tests/unit/resources/toolbox_invoice_test_page_hocr.xml
  tests/unit/test_document.py
  tests/unit/test_page.py
Labels: size: xl
