Repository googleapis/python-documentai-toolbox, pull requests merged in 2023-11, with the labels that each got.

#195 fix: Updates to hOCR Template to follow hOCR Spec
  google/cloud/documentai_toolbox/templates/hocr_document_template.xml.j2
  samples/snippets/test_convert_document_to_hocr_sample.py
  setup.py
  testing/constraints-3.10.txt
  testing/constraints-3.11.txt
  testing/constraints-3.7.txt
  testing/constraints-3.8.txt
  testing/constraints-3.9.txt
  tests/unit/resources/toolbox_invoice_test_0_hocr.xml
  tests/unit/test_document.py
Labels: size: m

#201 feat: Introduce compatibility with native namespace packages
  setup.py
  tests/unit/test_packaging.py
Labels: automerge, size: s

#208 build: treat warnings as errors
  google/cloud/documentai_toolbox/wrappers/document.py
  pytest.ini
Labels: automerge, size: s

#205 fix: Implement lazy-loading of properties to speed up initialization
  google/cloud/documentai_toolbox/wrappers/document.py
  google/cloud/documentai_toolbox/wrappers/page.py
  tests/unit/test_document.py
  tests/unit/test_gcs_utilities.py
  tests/unit/test_page.py
Labels: automerge, size: l

#211 build: Ignore `DeprecationWarning` from google-api-core
  pytest.ini
Labels: automerge, size: xs

#212 build: ignore warning from google-auth
  pytest.ini
Labels: size: xs

#200 fix: Prevent sorting entities labeled in Document AI Workbench
  google/cloud/documentai_toolbox/wrappers/document.py
  tests/unit/resources/hex_ids/patent.json
  tests/unit/test_document.py
Labels: size: m
