Repository googleapis/python-documentai-toolbox, pull requests merged in 2023-10, with the labels that each got.

#169 fix: Change `ocr_line` `<span>` to include all `ocr_word`
  google/cloud/documentai_toolbox/templates/hocr_document_template.xml.j2
  tests/unit/resources/toolbox_invoice_test_0_hocr.xml
Labels: automerge, size: m

#176 fix: `docai_utilities.py` to return `Optional`
  google/cloud/documentai_toolbox/utilities/docai_utilities.py
  google/cloud/documentai_toolbox/wrappers/entity.py
  google/cloud/documentai_toolbox/wrappers/page.py
  tests/unit/test_document.py
  tests/unit/test_entity.py
  tests/unit/test_page.py
Labels: size: m

#171 feat: Update Toolbox for OCR 2.0 features
  google/cloud/documentai_toolbox/wrappers/document.py
  google/cloud/documentai_toolbox/wrappers/page.py
  samples/snippets/quickstart_sample.py
  tests/unit/resources/pretrained-ocr-v2.0-2023-06-02_math_output.json
  tests/unit/resources/toolbox_invoice_test-with-symbols.json
  tests/unit/test_page.py
Labels: size: xl
