Repository googleapis/python-documentai-toolbox, pull requests merged in 2023-04, with the labels that each got.

#91 feat: Update Max Files per Batch Request to 1000
  google/cloud/documentai_toolbox/constants.py
  tests/unit/test_utilities.py
Labels: size: s

#95 chore: changed convert_external_annotation test
  samples/snippets/test_convert_external_annotations_sample.py
Labels: size: xs

#93 chore(deps): Update Dependencies for pandas and pikepdf
  samples/snippets/requirements.txt
  setup.py
Labels: automerge, size: xs

#96 feat: Added Export Images functionality
  google/cloud/documentai_toolbox/constants.py
  google/cloud/documentai_toolbox/wrappers/document.py
  google/cloud/documentai_toolbox/wrappers/entity.py
  samples/snippets/export_images_sample.py
  samples/snippets/test_export_images_sample.py
  setup.py
  tests/unit/resources/images/dl3-0.json
  tests/unit/test_document.py
  tests/unit/test_entity.py
Labels: size: m

#88 feat: Add Import Document from Batch Process Metadata & Operation
  docs/documentai_toolbox/utilities.rst
  google/cloud/documentai_toolbox/__init__.py
  google/cloud/documentai_toolbox/converters/config/converter_helpers.py
  google/cloud/documentai_toolbox/utilities/gcs_utilities.py
  google/cloud/documentai_toolbox/wrappers/document.py
  google/cloud/documentai_toolbox/wrappers/page.py
  samples/snippets/create_batches_sample.py
  samples/snippets/quickstart_sample.py
  tests/unit/test_converter.py
  tests/unit/test_converter_helpers.py
  tests/unit/test_document.py
  tests/unit/test_utilities.py
Labels: size: l

#103 chore: changed get_storage_client to add module name for analytics
  google/cloud/documentai_toolbox/converters/config/converter_helpers.py
  google/cloud/documentai_toolbox/utilities/gcs_utilities.py
  tests/unit/test_converter_helpers.py
Labels: size: s

#107 feat: Add blocks to PageWrapper
  google/cloud/documentai_toolbox/wrappers/page.py
  samples/snippets/quickstart_sample.py
  tests/unit/test_page.py
Labels: size: m

#104 feat: Added `form_fields_to_bigquery()` method
  google/cloud/documentai_toolbox/utilities/gcs_utilities.py
  google/cloud/documentai_toolbox/wrappers/document.py
  samples/snippets/entities_to_bigquery_sample.py
  tests/unit/test_document.py
Labels: size: l
