Repository googleapis/python-documentai-toolbox, pull requests merged in 2023-02, with the labels that each got.

#41 chore: update docs url
  .repo-metadata.json
  README.rst
Labels: size: xs

#44 chore: documentation fixes
  README.rst
  docs/README.rst
  google/cloud/documentai_toolbox/wrappers/document.py
Labels: size: m

#47 chore: changed test file name for quickstart sample
  samples/snippets/noxfile.py
  samples/snippets/quickstart_sample.py
  samples/snippets/test_quickstart_sample.py
Labels: samples, size: l

#42 chore: minor refactoring for readability/simplicity
  .gitignore
  google/cloud/documentai_toolbox/wrappers/document.py
  google/cloud/documentai_toolbox/wrappers/page.py
  tests/unit/test_page.py
Labels: size: m

#52 fix: Updated Pip install name in README
  README.rst
  samples/snippets/requirements.txt
  setup.py
Labels: size: s

#48 feat: Added Support for Form Fields
  google/cloud/documentai_toolbox/wrappers/document.py
  google/cloud/documentai_toolbox/wrappers/page.py
  tests/unit/resources/form_parser/pretrained-form-parser-v1.0-2020-09-23_full-output.json
  tests/unit/test_document.py
  tests/unit/test_page.py
Labels: size: xl

#54 samples: Added Table Parsing Sample
  samples/snippets/resources/form_with_tables.json
  samples/snippets/table_sample.py
  samples/snippets/test_table_sample.py
Labels: samples, size: xl

#51 feat: Add PDF Splitter
  google/cloud/documentai_toolbox/wrappers/document.py
  google/cloud/documentai_toolbox/wrappers/entity.py
  samples/snippets/split_pdf_sample.py
  samples/snippets/test_split_pdf_sample.py
  setup.py
  testing/constraints-3.10.txt
  testing/constraints-3.11.txt
  testing/constraints-3.7.txt
  testing/constraints-3.8.txt
  testing/constraints-3.9.txt
  tests/unit/resources/procurement_multi_document.pdf
  tests/unit/resources/splitter/procurement_splitter_output.json
  tests/unit/test_document.py
  tests/unit/test_entity.py
Labels: size: l

#50 feat: Add `entities_to_dict()` and `entities_to_bigquery()` to `Document` wrapper
  google/cloud/documentai_toolbox/wrappers/document.py
  google/cloud/documentai_toolbox/wrappers/entity.py
  samples/snippets/entities_to_bigquery_sample.py
  samples/snippets/requirements-test.txt
  samples/snippets/requirements.txt
  samples/snippets/test_entities_to_bigquery_sample.py
  samples/snippets/test_quickstart_sample.py
  setup.py
  testing/constraints-3.10.txt
  testing/constraints-3.11.txt
  testing/constraints-3.7.txt
  testing/constraints-3.8.txt
  testing/constraints-3.9.txt
  tests/unit/test_document.py
  tests/unit/test_entity.py
Labels: size: l

#58 docs: Update to README
  README.rst
Labels: size: s

#63 feat: added docproto to AnnotateFile convertor
  google/cloud/documentai_toolbox/__init__.py
  google/cloud/documentai_toolbox/converters/converters.py
  google/cloud/documentai_toolbox/converters/vision_helpers.py
  google/cloud/documentai_toolbox/wrappers/document.py
  samples/snippets/convert_document_to_vision_sample.py
  samples/snippets/test_convert_document_to_vision_sample.py
  setup.py
  tests/unit/test_document.py
  tests/unit/test_vision_helper.py
Labels: size: l

#64 chore: added init file to converter folder
  google/cloud/documentai_toolbox/converters/__init__.py
Labels: release-please:force-run, size: s
